function(add_sanitizer_address TARGET)
    message(STATUS "Address sanitizer enabled")
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        target_compile_options(${TARGET} PRIVATE -g -fsanitize=address)
        target_compile_options(${TARGET} PRIVATE -fno-sanitize=signed-integer-overflow)
        target_compile_options(${TARGET} PRIVATE -fno-sanitize-recover=all)
        target_compile_options(${TARGET} PRIVATE -fno-omit-frame-pointer)
        target_link_libraries(${TARGET} PRIVATE -fsanitize=address)
    elseif(MSVC)
        target_compile_options(${TARGET} PRIVATE -fsanitize=address)
        target_link_libraries(${TARGET} PRIVATE -fsanitize=address)
    endif()
endfunction()

function(add_sanitizer_thread TARGET)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        message(STATUS "Address sanitizer enabled")
        target_compile_options(${TARGET} PRIVATE -g -fsanitize=thread)
        target_compile_options(${TARGET} PRIVATE -fno-sanitize=signed-integer-overflow)
        target_compile_options(${TARGET} PRIVATE -fno-sanitize-recover=all)
        target_compile_options(${TARGET} PRIVATE -fno-omit-frame-pointer)
        target_link_libraries(${TARGET} PRIVATE -fsanitize=thread)
    elseif(MSVC)
        message("Thread sanitizer not supported.")
    endif()
endfunction()
